# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_tag_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=1000),
        ),
    ]
