# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171217_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentvote',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
