# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_commentvote_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='downvote',
            new_name='vote',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='upvote',
        ),
        migrations.AddField(
            model_name='reply',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
