# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-17 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20171217_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply',
            field=models.TextField(max_length=1000),
        ),
    ]
