# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20180118_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='propic',
            field=models.FileField(default=b'/static/home/images/default.png', upload_to=b''),
        ),
    ]
