# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-18 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20180118_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='propic',
            field=models.FileField(default=b'default.png', upload_to=b''),
        ),
    ]
